name: fullstack-application

getVotes:
  component: "@serverless/function"
  inputs:
    name: getVotes
    region: eu-central-1
    code: ./api
    handler: getVotes.getVotes
getTime:
  component: "@serverless/function"
  inputs:
    name: getTime
    region: eu-central-1
    code: ./api
    handler: getTime.getTime

restApi:
  component: "@serverless/api"
  inputs:
    name: "rest-test-api"
    region: eu-central-1
    endpoints:
      - path: /time
        method: GET
        function: ${getTime}
      - path: /votes
        method: GET
        function: ${getVotes}

frontend:
  component: "@serverless/website"
  inputs:
    name: react-frontend
    region: eu-central-1
    code:
      src: build
      root: frontend
      hook: npm run build
    env:
      apiUrl: ${restApi.url}
    # domain: www.serverlessmetrics.com # Insert your custom domain here after registering it on Route53
