# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.4.1
    
    - name: install serverless and plugins
      run: npm i serverless
    - name: Deploy api and lambda funcitons
      run: echo Hello, world!
    - run: cd api
    - run: npm i
    - run: env NODE_ENV=development serverless deploy --debug --region eu-central-1 --env development
    - run: cd ..
      

    # Runs a set of commands using the runners shell
    - name: Build and deploy frontend
      run: cd frontend
    - run: npm i
    - run: serverless --debug --region eu-central-1 --bucketName gemeinde-im-netz-frontend-dev --env development
